In [1]:
import torch
import numpy as np

In [2]:
torch.cuda.is_available()

True

In [3]:
torch.cuda.device_count()

1

In [4]:
torch.cuda.device(0)

In [3]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 3080'

In [7]:
first_tens = torch.tensor([[12,10,11,9],[13,15,14,16]])
second_tens = torch.tensor([[1,2,3,4],[5,6,7,8]])

add_tens = first_tens + second_tens
print(add_tens)
print(add_tens.size())

tensor([[13, 12, 14, 13],
        [18, 21, 21, 24]])
torch.Size([2, 4])


In [9]:
sub_tens = first_tens - second_tens
print (sub_tens)

tensor([[11,  8,  8,  5],
        [ 8,  9,  7,  8]])


In [10]:
print(torch.__version__)

2.9.0+cu126


In [11]:
if torch.cuda.is_available(): device = "cuda"
else: device = "cpu"
print(device)

cuda


In [12]:


tens_a = torch.tensor([[10,11,12,13],[14,15,16,17]],device=device)
tens_b = torch.tensor([[18,19,20,21],[22,23,24,25]],device=device)
multi_tens = tens_a * tens_b
print(multi_tens)
     


tensor([[180, 209, 240, 273],
        [308, 345, 384, 425]], device='cuda:0')


In [14]:
# initialize a tensor from a Python list
tensor_from_list=torch.tensor([1,2,3,4,5])
# initialize a tensor from a tuple
tensor_from_tuple=torch.tensor((6,7,8,9,10))
print("Tensor from list:",tensor_from_list)
print("Tensor from tuple:",tensor_from_tuple)
     


Tensor from list: tensor([1, 2, 3, 4, 5])
Tensor from tuple: tensor([ 6,  7,  8,  9, 10])


In [15]:
# initialize a tensor from a ndarray
tensor_from_array=torch.tensor(np.array([11,12,13,14,15]))
print("Tensor from array:",tensor_from_array)

Tensor from array: tensor([11, 12, 13, 14, 15])


In [16]:


tensor_emp = torch.empty(3,4)
print("tensor_emp :",tensor_emp)
tensor_zeros = torch.zeros(3,4)
print("tensor_zeros :",tensor_zeros)
tensor_ones= torch.ones(3,4)
print("tensor_ones :",tensor_ones)
     


tensor_emp : tensor([[0.0000e+00, 0.0000e+00, 1.3526e-13, 0.0000e+00],
        [1.3811e-14, 0.0000e+00, 2.7597e-21, 4.3087e-41],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor_zeros : tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor_ones : tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:


# tensors initialized by size with random values
# returns a tensor filled with random numbers from a uniform distribution
tensor_rand_un = torch.rand(4,5)
print("tensor_rand_un :",tensor_rand_un)
# returns a tensor filled with random numbers from a normal distribution
tensor_rand_norm = torch.randn(4,5)
print("tensor_rand_norm :",tensor_rand_norm)
# returns a tensor filled with random integers generated uniformly
tensor_rand_int = torch.randint(5,10,(4,5))
print("tensor_rand_int :",tensor_rand_int)
     


tensor_rand_un : tensor([[0.0220, 0.8996, 0.2498, 0.4502, 0.4417],
        [0.3644, 0.7174, 0.4444, 0.6461, 0.3354],
        [0.6045, 0.4446, 0.2973, 0.8309, 0.7232],
        [0.0290, 0.9828, 0.9558, 0.6245, 0.3499]])
tensor_rand_norm : tensor([[-0.8207,  1.0015,  1.5360, -0.3194,  0.2310],
        [-0.5531,  2.3724, -0.8632,  0.2606,  0.3567],
        [-0.2289,  1.2355, -0.5369, -0.9052,  0.1745],
        [ 1.1978,  0.6069,  1.5267, -0.1536,  0.3735]])
tensor_rand_int : tensor([[7, 7, 9, 5, 6],
        [5, 6, 7, 5, 6],
        [5, 9, 6, 5, 5],
        [7, 8, 9, 6, 9]])


In [25]:
#@title Indexing 2-dim tensor example
two_dim_tensor=torch.tensor([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24]])
two_dim_tensor[1][3]


tensor(10)

In [29]:
torch.unbind(two_dim_tensor)

(tensor([1, 2, 3, 4, 5, 6]),
 tensor([ 7,  8,  9, 10, 11, 12]),
 tensor([13, 14, 15, 16, 17, 18]),
 tensor([19, 20, 21, 22, 23, 24]))